### ISSUE TITLE
横竖屏幕切换的时候，能重绘图表么？

### ISSUE THREAD

**Issue by vellengs** [Ovilia/echarts-with-ionics#1]
我整了一个图表，横竖屏切换的时候，不会重绘，强制调用resize 也没效果，不知道还有没别的api ?。

**Comment by Ovilia** [comment]
你首先检查一下图表的高度和宽度对不对，调用 resize 只要容器宽度和高度是新的，应该会是对的

**Comment by vellengs** [comment]
确实 resize 是可以调整，不过 横竖屏幕切换的时候不会马上起作用。

`  window.addEventListener("orientationchange", () => {
        let self = this;
            setTimeout(() => {
                self.chart.resize();
            }, 900);
        }, true);
`
我不得不使用延迟执行。有没更好的办法，这个延迟可能不可靠，设大了体验也不好？

**Comment by Ovilia** [comment]
`window.onresize = chart.resize` 可以吗？

**Comment by Ovilia** [comment]
不行的话看看 https://stackoverflow.com/questions/12452349/mobile-viewport-height-after-orientation-change
